name: "Zola(with indexing-zh and indexing-ja feature) Deploy to Pages"
description: "Build and deploy a Zola(with indexing-zh and indexing-ja feature) site to GitHub Pages"
author: "DeadPoetSpoon"
runs:
  using: "docker"
  image: "Dockerfile"
branding:
  icon: "zap"
  color: "green"
